
export const languagesContent = [
  {place: 'select', name: 'Select', value: 'select', label: 'Select'},
  {place: 'english', name: 'English', value: 'english', label: 'English'},
  {place: 'russian', name: 'Russian', value: 'russian', label: 'Russian'},
  {place: 'hebrew', name: 'Hebrew', value: 'hebrew', label: 'Hebrew'},
  {place: 'french', name: 'French', value: 'french', label: 'French'},
  {place: 'spanish', name: 'Spanish', value: 'spanish', label: 'Spanish'},
  {place: 'italian', name: 'Italian', value: 'italian', label: 'Italian'},
  {place: 'georgian', name: 'Georgian', value: 'georgian', label: 'Georgian'},
  {place: 'romanian', name: 'Romanian', value: 'romanian', label: 'Romanian'},
  {place: 'japanese', name: 'Japanese', value: 'japanese', label: 'Japanese'},
  {place: 'german', name: 'German', value: 'german', label: 'German'},
];


export const languagesInterface = [
  // {place: 'english', name: 'English', label: 'English', value: 'english', icon: 'flag-icon-gb'},
  // {place: 'hebrew', name: 'Hebrew', label: 'Hebrew', value: 'hebrew', icon: 'flag-icon-il'},
  // {place: 'russian', name: 'Russian', label: 'Russian', value: 'russian', icon: 'flag-icon-ru'},
  // {place: 'french', name: 'French', label: 'French', value: 'french', icon: 'flag-icon-fr'},
  // {place: 'spanish', name: 'Spanish', label: 'Spanish', value: 'spanish', icon: 'flag-icon-es'},
  //
  // {place: 'achinese', name: 'Achinese', label: 'Achinese', value: 'achinese', icon: 'flag-icon-es'},
  // {place: 'afrikaans', name: 'Afrikaans', label: 'Afrikaans', value: 'afrikaans', icon: 'flag-icon-es'},
  // {place: 'albanian', name: 'Albanian', label: 'Albanian', value: 'albanian', icon: 'flag-icon-es'},
  // {place: 'amharic', name: 'Amharic', label: 'Amharic', value: 'amharic', icon: 'flag-icon-es'},
  // {place: 'armenian', name: 'Armenian', label: 'Armenian', value: 'armenian', icon: 'flag-icon-es'},
  // {place: 'azerbaijani', name: 'Azerbaijani', label: 'Azerbaijani', value: 'azerbaijani', icon: 'flag-icon-es'},
  // {place: 'basque', name: 'Basque', label: 'Basque', value: 'basque', icon: 'flag-icon-es'},
  // {place: 'bulgarian', name: 'Bulgarian', label: 'Bulgarian', value: 'bulgarian', icon: 'flag-icon-es'},
  // {place: 'burmese', name: 'Burmese', label: 'Burmese', value: 'burmese', icon: 'flag-icon-es'},
  // {place: 'catalan', name: 'Catalan', label: 'Catalan', value: 'catalan', icon: 'flag-icon-es'},
  // {place: 'chinese', name: 'Chinese', label: 'Chinese', value: 'chinese', icon: 'flag-icon-es'},
  // {place: 'montenegrin', name: 'Montenegrin', label: 'Montenegrin', value: 'montenegrin', icon: 'flag-icon-es'},
  // {place: 'corsican', name: 'Corsican', label: 'Corsican', value: 'corsican', icon: 'flag-icon-es'},
  // {place: 'czech', name: 'Czech', label: 'Czech', value: 'czech', icon: 'flag-icon-es'},
  // {place: 'danish', name: 'Danish', label: 'Danish', value: 'danish', icon: 'flag-icon-es'},
  // {place: 'dutch', name: 'Dutch; Flemish', label: 'Dutch', value: 'dutch', icon: 'flag-icon-es'},
  // {place: 'esperanto', name: 'Esperanto', label: 'Esperanto', value: 'esperanto', icon: 'flag-icon-es'},
  // {place: 'estonian', name: 'Estonian', label: 'Estonian', value: 'estonian', icon: 'flag-icon-es'},
  // {place: 'filipino', name: 'Filipino; Pilipino', label: 'Filipino', value: 'filipino', icon: 'flag-icon-es'},
  // {place: 'finnish', name: 'Finnish', label: 'Finnish', value: 'finnish', icon: 'flag-icon-es'},
  // {place: 'georgian', name: 'Georgian', label: 'Georgian', value: 'georgian', icon: 'flag-icon-es'},
  // {place: 'german', name: 'German', label: 'German', value: 'german', icon: 'flag-icon-es'},
  // {place: 'geez', name: 'Geez', label: 'Geez', value: 'geez', icon: 'flag-icon-es'},
  // {place: 'irish', name: 'Irish', label: 'Irish', value: 'irish', icon: 'flag-icon-es'},
  // {place: 'greek', name: 'Greek', label: 'Greek', value: 'greek', icon: 'flag-icon-es'},
  // {place: 'hausa', name: 'Hausa', label: 'Hausa', value: 'hausa', icon: 'flag-icon-es'},
  // {place: 'hindi', name: 'Hindi', label: 'Hindi', value: 'hindi', icon: 'flag-icon-es'},
  // {place: 'croatian', name: 'Croatian', label: 'Croatian', value: 'croatian', icon: 'flag-icon-es'},
  // {place: 'hungarian', name: 'Hungarian', label: 'Hungarian', value: 'hungarian', icon: 'flag-icon-es'},
  // {place: 'icelandic', name: 'Icelandic', label: 'Icelandic', value: 'icelandic', icon: 'flag-icon-es'},
  // {place: 'indonesian', name: 'Indonesian', label: 'Indonesian', value: 'indonesian', icon: 'flag-icon-es'},
  // {place: 'italian', name: 'Italian', label: 'Italian', value: 'italian', icon: 'flag-icon-es'},
  // {place: 'javanese', name: 'Javanese', label: 'Javanese', value: 'javanese', icon: 'flag-icon-es'},
  // {place: 'japanese', name: 'Japanese', label: 'Japanese', value: 'japanese', icon: 'flag-icon-es'},
  // {place: 'korean', name: 'Korean', label: 'Korean', value: 'korean', icon: 'flag-icon-es'},
  // {place: 'latin', name: 'Latin', label: 'Latin', value: 'latin', icon: 'flag-icon-es'},
  // {place: 'latvian', name: 'Latvian', label: 'Latvian', value: 'latvian', icon: 'flag-icon-es'},
  // {place: 'lithuanian', name: 'Lithuanian', label: 'Lithuanian', value: 'lithuanian', icon: 'flag-icon-es'},
  // {place: 'macedonian', name: 'Macedonian', label: 'Macedonian', value: 'macedonian', icon: 'flag-icon-es'},
  // {place: 'malay', name: 'Malay', label: 'Malay', value: 'malay', icon: 'flag-icon-es'},
  // {place: 'maltese', name: 'Maltese', label: 'Maltese', value: 'maltese', icon: 'flag-icon-es'},
  // {place: 'norwegian', name: 'Norwegian', label: 'Norwegian', value: 'norwegian', icon: 'flag-icon-es'},
  // {place: 'persian', name: 'Persian', label: 'Persian', value: 'persian', icon: 'flag-icon-es'},
  // {place: 'polish', name: 'Polish', label: 'Polish', value: 'polish', icon: 'flag-icon-es'},
  // {place: 'portuguese', name: 'Portuguese', label: 'Portuguese', value: 'portuguese', icon: 'flag-icon-es'},
  // {place: 'romansh', name: 'Romansh', label: 'Romansh', value: 'romansh', icon: 'flag-icon-es'},
  // {place: 'romany', name: 'Romany', label: 'Romany', value: 'romany', icon: 'flag-icon-es'},
  // {place: 'romanian', name: 'Romanian', label: 'Romanian', value: 'romanian', icon: 'flag-icon-es'},
  // {place: 'slovak', name: 'Slovak', label: 'Slovak', value: 'slovak', icon: 'flag-icon-es'},
  // {place: 'slovenian', name: 'Slovenian', label: 'Slovenian', value: 'slovenian', icon: 'flag-icon-es'},
  // {place: 'serbian', name: 'Serbian', label: 'Serbian', value: 'serbian', icon: 'flag-icon-es'},
  // {place: 'swedish', name: 'Swedish', label: 'Swedish', value: 'swedish', icon: 'flag-icon-es'},
  // {place: 'tahitian', name: 'Tahitian', label: 'Tahitian', value: 'tahitian', icon: 'flag-icon-es'},
  // {place: 'thai', name: 'Thai', label: 'Thai', value: 'thai', icon: 'flag-icon-es'},
  // {place: 'turkish', name: 'Turkish', label: 'Turkish', value: 'turkish', icon: 'flag-icon-es'},
  // {place: 'ukrainian', name: 'Ukrainian', label: 'Ukrainian', value: 'ukrainian', icon: 'flag-icon-es'},
  // {place: 'urdu', name: 'Urdu', label: 'Urdu', value: 'urdu', icon: 'flag-icon-es'},
  // {place: 'uzbek', name: 'Uzbek', label: 'Uzbek', value: 'uzbek', icon: 'flag-icon-es'},
];
