import {NgModule, NO_ERRORS_SCHEMA} from '@angular/core';
import {NativeScriptModule} from '@nativescript/angular';

import {AppRoutingModule} from '@src/app/app-routing.module.tns';
import {AppComponent} from '@src/app/app.component';
import {AutoGeneratedComponent} from '@src/app/auto-generated/auto-generated.component';
import {PopUpBonvinoComponent} from '@src/app/schemas/pop-up-bonvino/pop-up-bonvino.component';
import {HistoryComponent} from '@src/app/history/history.component';
import {VisitinghoursComponent} from '@src/app/visitinghours/visitinghours.component';
import {WineryDeletedComponent} from '@src/app/wineries-designed/winery-deleted/winery-deleted.component';
import {WineryChangelogComponent} from '@src/app/wineries-designed/winery-changelog/winery-changelog.component';
import {WineryHistoryComponent} from '@src/app/wineries-designed/winery-history/winery-history.component';
import {MenuSchemaComponent} from '@src/app/schemas/menu-schema/menu-schema.component';
import {AdditionalSchemaComponent} from '@src/app/schemas/additional-schema/additional-schema.component';
import {AdditionalViewSchemaComponent} from '@src/app/schemas/additional-view-schema/additional-view-schema.component';
import {WineChangelogComponent} from '@src/app/wines-designed/wine-changelog/wine-changelog.component';
import {DescriptionGradesAddComponent} from '@src/app/wines-designed/description-grades-add/description-grades-add.component';
import {DescriptionGradesViewComponent} from '@src/app/wines-designed/description-grades-view/description-grades-view.component';
import {TabsBarComponent} from '@src/app/schemas/tabs-bar/tabs-bar.component';
import {ButtonRowComponent} from '@src/app/schemas/button-row/button-row.component';
import {AdminBottleComponent} from '@src/app/admin/admin-bottle/admin-bottle.component';
import {TemperatureInputBonvinoComponent} from '@src/app/schemas/temperature-input-bonvino/temperature-input-bonvino.component';
import {TemperatureViewBonvinoComponent} from '@src/app/schemas/temperature-view-bonvino/temperature-view-bonvino.component';
import {OriginInputBonvinoComponent} from '@src/app/schemas/origin-input-bonvino/origin-input-bonvino.component';
import {OriginViewBonvinoComponent} from '@src/app/schemas/origin-view-bonvino/origin-view-bonvino.component';
import {SubblockViewBonvinoComponent} from '@src/app/schemas/subblock-view-bonvino/subblock-view-bonvino.component';
import {SubblockInputBonvinoComponent} from '@src/app/schemas/subblock-input-bonvino/subblock-input-bonvino.component';
import {BlocksConstructorComponent} from '@src/app/admin/blocks-constructor/blocks-constructor.component';
import {AdditionalListDesignedComponent} from '@src/app/lists/additional-list-designed/additional-list-designed.component';
import {PersonSearchComponent} from '@src/app/schemas/person-search/person-search.component';
import {PersonOneRowComponent} from '@src/app/schemas/person-one-row/person-one-row.component';
import {LanguageListComponent} from '@src/app/language/language-list/language-list.component';
import {VineyardOneDesignedComponent} from '@src/app/vineyard-designed/vineyard-one-designed/vineyard-one-designed.component';
import {VineyardCreateDesignedComponent} from '@src/app/vineyard-designed/vineyard-create-designed/vineyard-create-designed.component';
import {VineyardBasicDesignedComponent} from '@src/app/vineyard-designed/vineyard-basic-designed/vineyard-basic-designed.component';
import {VineyardAdditionalDesignedComponent} from '@src/app/vineyard-designed/vineyard-additional-designed/vineyard-additional-designed.component';
import {VineyardMenuDesignedComponent} from '@src/app/vineyard-designed/vineyard-menu-designed/vineyard-menu-designed.component';
import {TextComplicatedComponent} from '@src/app/language/text-complicated/text-complicated.component';
import {WineriesSecondComponent} from '@src/app/wineries-designed/wineries-second/wineries-second.component';
import {CompetitionAddComponent} from '@src/app/competition-designed/competition-add/competition-add.component';
import {CompetitionOneComponent} from '@src/app/competition-designed/competition-one/competition-one.component';
import {CompetitionBasicComponent} from '@src/app/competition-designed/competition-basic/competition-basic.component';
import {CompetitionMenuComponent} from '@src/app/competition-designed/competition-menu/competition-menu.component';
import {CompetitionAdditionalComponent} from '@src/app/competition-designed/competition-additional/competition-additional.component';
import {CompetitionSelectComponent} from '@src/app/schemas/competition-select/competition-select.component';
import {CompetitionOneRowComponent} from '@src/app/schemas/competition-one-row/competition-one-row.component';
import {AwardOneRowComponent} from '@src/app/schemas/award-one-row/award-one-row.component';
import {WineOneUniversalComponent} from '@src/app/wines-designed/wine-one-universal/wine-one-universal.component';
import {WineOneUniversalSubscreenComponent} from '@src/app/wines-designed/wine-one-universal-subscreen/wine-one-universal-subscreen.component';
import {CompetitionWineSelectComponent} from '@src/app/schemas/competition-wine-select/competition-wine-select.component';
import {CompetitionGrantAwardsComponent} from '@src/app/competition-designed/competition-grant-awards/competition-grant-awards.component';
import {WineryListDesignedComponent} from '@src/app/lists/winery-list-designed/winery-list-designed.component';
import {WinesShortDesignedComponent} from '@src/app/wines-designed/wines-short-designed/wines-short-designed.component';
import {CompetitionPossibleAwardsComponent} from '@src/app/competition-designed/competition-possible-awards/competition-possible-awards.component';
import {ExistedSchemaFormComponent} from '@src/app/schemas/existed-schema-form/existed-schema-form.component';
import {WineryShortComponent} from '@src/app/wineries-designed/winery-short/winery-short.component';
import {WineryShortSubscreenComponent} from '@src/app/wineries-designed/winery-short-subscreen/winery-short-subscreen.component';
import {EventShortDesignedComponent} from '@src/app/event-designed/event-short-designed/event-short-designed.component';
import {EventShortSubscreenComponent} from '@src/app/event-designed/event-short-subscreen/event-short-subscreen.component';
import {AdditionalSearchSchemaComponent} from '@src/app/schemas/additional-search-schema/additional-search-schema.component';
import {MapHiddenComponent} from '@src/app/schemas/map-hidden/map-hidden.component';
import {MapSubscreenComponent} from '@src/app/schemas/map-subscreen/map-subscreen.component';
import {WineAutodecriptionComponent} from '@src/app/wines-designed/wine-autodecription/wine-autodecription.component';
import {WineDescriptionComponent} from '@src/app/wines-designed/wine-description/wine-description.component';
import {WineDescriptionSubscreenComponent} from '@src/app/wines-designed/wine-description-subscreen/wine-description-subscreen.component';
import {FindWineComponent} from '@src/app/schemas/find-wine/find-wine.component';
import {BengatContactsComponent} from '@src/app/schemas/bengat-contacts/bengat-contacts.component';
import {TitleComponent} from '@src/app/language/title/title.component';
import {WinesShopAddSubscreenComponent} from '@src/app/wines-designed/wines-shop-add-subscreen/wines-shop-add-subscreen.component';
import {SubrouterComponent} from '@src/app/schemas/subrouter/subrouter.component';


// Uncomment and add to NgModule imports if you need to use two-way binding and/or HTTP wrapper
// import { NativeScriptFormsModule, NativeScriptHttpClientModule } from '@nativescript/angular';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    PopUpBonvinoComponent,
    HistoryComponent,
    VisitinghoursComponent,
    WineryDeletedComponent,
    WineryChangelogComponent,
    WineryHistoryComponent,
    MenuSchemaComponent,
    AdditionalSchemaComponent,
    AdditionalViewSchemaComponent,
    WineChangelogComponent,
    DescriptionGradesAddComponent,
    DescriptionGradesViewComponent,
    TabsBarComponent,
    ButtonRowComponent,
    AdminBottleComponent,
    TemperatureInputBonvinoComponent,
    TemperatureViewBonvinoComponent,
    OriginInputBonvinoComponent,
    OriginViewBonvinoComponent,
    SubblockViewBonvinoComponent,
    SubblockInputBonvinoComponent,
    BlocksConstructorComponent,
    AdditionalListDesignedComponent,
    PersonSearchComponent,
    PersonOneRowComponent,
    LanguageListComponent,
    VineyardOneDesignedComponent,
    VineyardCreateDesignedComponent,
    VineyardBasicDesignedComponent,
    VineyardAdditionalDesignedComponent,
    VineyardMenuDesignedComponent,
    TextComplicatedComponent,
    WineriesSecondComponent,
    CompetitionAddComponent,
    CompetitionOneComponent,
    CompetitionBasicComponent,
    CompetitionMenuComponent,
    CompetitionAdditionalComponent,
    CompetitionSelectComponent,
    CompetitionOneRowComponent,
    AwardOneRowComponent,
    WineOneUniversalComponent,
    WineOneUniversalSubscreenComponent,
    CompetitionWineSelectComponent,
    CompetitionGrantAwardsComponent,
    WineryListDesignedComponent,
    WinesShortDesignedComponent,
    CompetitionPossibleAwardsComponent,
    ExistedSchemaFormComponent,
    WineryShortComponent,
    WineryShortSubscreenComponent,
    EventShortDesignedComponent,
    EventShortSubscreenComponent,
    AdditionalSearchSchemaComponent,
    MapHiddenComponent,
    MapSubscreenComponent,
    WineAutodecriptionComponent,
    WineDescriptionComponent,
    WineDescriptionSubscreenComponent,
    FindWineComponent,
    BengatContactsComponent,
    TitleComponent,
    WinesShopAddSubscreenComponent,
    SubrouterComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
